// <auto-generated />
using System;
using BookBook.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookBook.Repository.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20231018155143_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BookBook.Models.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("AuthorId");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DayOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            Country = "Kien Giang",
                            DayOfBirth = new DateTime(2000, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Pham",
                            LastName = "Pham",
                            PhoneNumber = "0987654321"
                        },
                        new
                        {
                            Id = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            Country = "Kien Giang",
                            DayOfBirth = new DateTime(2000, 11, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Nguyen",
                            LastName = "Nguyen",
                            PhoneNumber = "0987654321"
                        });
                });

            modelBuilder.Entity("BookBook.Models.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("BookId");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("char(36)");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66313185-cf8d-43c0-b520-78f1a0eed791"),
                            AuthorId = new Guid("3d490a70-94ce-4d15-9494-5248280c2ce3"),
                            BookName = "Sach so 1",
                            CreatedDate = new DateTime(2023, 10, 18, 15, 51, 43, 326, DateTimeKind.Utc).AddTicks(7563),
                            Price = 50000
                        },
                        new
                        {
                            Id = new Guid("02f85402-7d36-40fc-bcf7-f3eabebc3061"),
                            AuthorId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            BookName = "Sach so 1",
                            CreatedDate = new DateTime(2023, 10, 18, 15, 51, 43, 326, DateTimeKind.Utc).AddTicks(7613),
                            Price = 50000
                        });
                });

            modelBuilder.Entity("BookBook.Models.Models.Book", b =>
                {
                    b.HasOne("BookBook.Models.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookBook.Models.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
